#!/usr/bin/env bash
#This script displays the content of /etc/pswd showing username etc
while IFS=: read -r username _ userid _ _ homedir _
do 
    echo "$username:$userid:$homedir"
done < /etc/passwd
