#!/usr/bin/env bash
# This script loops from 1 to 10 and display bad luck, good luckor Best School
i=1
while [ $i -le 10 ]
do 
if [ $i -eg 4 ]
then
echo "bad luck"
elif [ $i -eg 8 ]
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
