#!/usr/bin/env bash
# This script manages the manage_my_process daemon

pidfile="/var/run/my_process.pid"

case "$1" in
    start)
        ./manage_my_process &
        echo $! > "$pidfile"
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat "$pidfile")"
        rm -f "$pidfile"
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat "$pidfile")"
        rm -f "$pidfile"
        ./manage_my_process &
        echo $! > "$pidfile"
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

