#!/usr/bin/env bash
# This script writes "I am alive!" to /tmp/my_process indefinitely
echo "manage_my_process" > /proc/self/comm
while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
